### ISSUE TITLE
Delayed Jobs crashing/stopping

### ISSUE THREAD

**Issue by oveits** [oveits/ProvisioningEngine#11]
The second time within a few hours, we see, that the Delayed Jobs are stopped:
```
provisioningengine@ProvisioningEngine:~/ProvisioningEnginev0.5.15$ ./status
Web Portal (productive):   running (PID=22822) on port 3000
Web Portal (development):   running (PID=19406) on port 3001
Delayed Jobs: not running
```
This leads to objects hanging in the status "waiting for provisioning" and "synchronization in progress" forever:
![image](https://cloud.githubusercontent.com/assets/8299115/12317202/280a50e2-ba8f-11e5-832a-48ee03004065.png)

ProvisioningTasks are hanging:
![image](https://cloud.githubusercontent.com/assets/8299115/12317225/793a1f1a-ba8f-11e5-91dc-ba8cc16cd09a.png)

Workaround is to restart the service like follows:
```
provisioningengine@ProvisioningEngine:~/ProvisioningEnginev0.5.15$ ./startDelayedJobs.sh
Delayed Jobs started: PID=29548
```

However, this is not a solution, if the Delayed Jobs are crashing frequently.

How to troubleshoot crashed processes like this? Are there any logs? Note, that we cannot easily upgraded the Delayed Jobs gem, since the new versions have a problem (retry, remove buttons are not shown in Delayed Jobs Web).

**Comment by oveits** [comment]
Is stopped again. If I restart, Delayed Jobs is stopped after some seconds again. Now trying a reboot.

**Comment by oveits** [comment]
This is the output, if I start delayed jobs in the foreground:
```
./startDelayedJobs_foreground.sh
[Worker(host:ProvisioningEngine pid:23008)] Starting job worker
[Worker(host:ProvisioningEngine pid:23008)] Job Site.synchronizeAllSynchronously (id=1410) RUNNING
"------------- HttpPostRequest POST Data to http://192.168.113.104:80/ProvisioningEngine -----------------"
"{\"action\"=>\"Show Sites\", \"customerName\"=>\"ACME01\", \"OSVIP\"=>\"192.168.113.212\", \"OSVMgmtIP\"=>\"192.168.113.212\", \"OSVSshPort\"=>\"22\", \"XPRIP\"=>\"192.168.113.212\", \"UCIP\"=>\"192.168.113.208\", \"WebCDCIP\"=>\"UNKNOWN\", \"OSVauthUsername\"=>\"srx\", \"OSVauthPassword\"=>\"2GwN!gb4\", \"OSVauthPasswordRoot\"=>\"Pa$$w0rd!\", \"OSVauthPasswordSysad\"=>\"Asd123!.\", \"XPRauthUsername\"=>\"Administrator\", \"XPRauthPassword\"=>\"Pa$$w0rd\", \"UCauthUsername\"=>\"Administrator@system\", \"UCauthPassword\"=>\"Asd123!.\", \"FPCREATEOmit\"=>\"true\", \"FPAFOmit\"=>\"true\"}"
"----------------------------------------------------------"
"------------------resulttext------------------"
"resulttext = connection timout for http://192.168.113.104:80/ProvisioningEngine at 2016-01-14 12:45:14 +0100"
"returnvalue = 8"
"------------------resulttext------------------"
"SSSSSSSSSSSSSSSSSSSSSSSSS    Site.synchronizeAll responseBody    SSSSSSSSSSSSSSSSSSSSSSSSS"
"8"
synchronizeAllSynchronously: ERROR: wrong responseBody type (Fixnum) instead of String)
Delayed Jobs started: PID=
provisioningengine@ProvisioningEngine:~/ProvisioningEnginev0.5.15$
```
We can see that the Delayed Jobs is stopped with the abort found on "app/models/provisioningobject.rb"
```
abort "synchronizeAllSynchronously: ERROR: wrong responseBody type (#{responseBody.class.name}) instead of String)" unless responseBody.is_a?(String)
```
With this abort, the task should be retried, but instead, delayed jobs worker stops.

The task is a synchronizeAllSynchronously. Here the data from https://192.168.113.105/delayed_job/pending#1410 (will be removed from the queue now):
```
ID
1410 Retry or Remove or Reload Job
Priority
0
Attempts
0
Handler
--- !ruby/object:Delayed::PerformableMethod
object: !ruby/class 'Site'
method_name: :synchronizeAllSynchronously
args:
- - !ruby/object:Customer
    attributes:
      id: 113
      name: ACME01
      created_at: 2015-02-02 08:26:06.399517000 Z
      updated_at: 2015-09-02 20:11:27.115936000 Z
      status: deletion failed (timed out); trying again
      target_id: 44
      language: german
  - !ruby/object:Customer
    attributes:
      id: 114
      name: CCMFed
      created_at: 2015-02-02 08:56:59.226939000 Z
      updated_at: 2015-09-02 19:54:29.010734000 Z
      status: deletion failed (timed out); trying again
      target_id: 44
      language: englishGB
  - !ruby/object:Customer
    attributes:
      id: 190
      name: ExampleCustomerV8
      created_at: 2015-05-07 13:49:11.942109000 Z
      updated_at: 2015-09-02 19:03:34.693582000 Z
      status: deletion failed (timed out); trying again
      target_id: 44
      language: 
- false
- true
Run At
about 14 hours ago
```
